IF OBJECT_ID('dbo.z_ACDQueue', 'U') IS NULL    select top(0) * into z_ACDQueue								 from  ACDQueue                     ELSE  TRUNCATE TABLE  z_ACDQueue						
IF OBJECT_ID('dbo.z_Agent', 'U') IS NULL    select top(0) * into z_Agent								 from  Agent                            ELSE  TRUNCATE TABLE  z_Agent							
IF OBJECT_ID('dbo.z_AgentAssignment', 'U') IS NULL    select top(0) * into z_AgentAssignment						 from  AgentAssignment                  ELSE  TRUNCATE TABLE  z_AgentAssignment				
IF OBJECT_ID('dbo.z_AgentSkill', 'U') IS NULL    select top(0) * into z_AgentSkill							 from  AgentSkill                       ELSE  TRUNCATE TABLE  z_AgentSkill					
IF OBJECT_ID('dbo.z_AreaCodes', 'U') IS NULL    select top(0) * into z_AreaCodes							 from  AreaCodes                        ELSE  TRUNCATE TABLE  z_AreaCodes						
IF OBJECT_ID('dbo.z_AudioMessage', 'U') IS NULL    select top(0) * into z_AudioMessage							 from  AudioMessage                 ELSE  TRUNCATE TABLE  z_AudioMessage					
IF OBJECT_ID('dbo.z_Backlog_I						', 'U') IS NULL    select top(0) * into z_Backlog_I							 from  Backlog_I                        ELSE  TRUNCATE TABLE  z_Backlog_I						
IF OBJECT_ID('dbo.z_CallHistory					', 'U') IS NULL    select top(0) * into z_CallHistory							 from  CallHistory                      ELSE  TRUNCATE TABLE  z_CallHistory					
IF OBJECT_ID('dbo.z_CallTimeRules					', 'U') IS NULL    select top(0) * into z_CallTimeRules						 from  CallTimeRules                    ELSE  TRUNCATE TABLE  z_CallTimeRules					
IF OBJECT_ID('dbo.z_CampaignCallTimeRuleMap		', 'U') IS NULL    select top(0) * into z_CampaignCallTimeRuleMap				 from  CampaignCallTimeRuleMap          ELSE  TRUNCATE TABLE  z_CampaignCallTimeRuleMap		
IF OBJECT_ID('dbo.z_CampaignList					', 'U') IS NULL    select top(0) * into z_CampaignList							 from  CampaignList                 ELSE  TRUNCATE TABLE  z_CampaignList					
IF OBJECT_ID('dbo.z_CampaignLookup				', 'U') IS NULL    select top(0) * into z_CampaignLookup						 from  CampaignLookup                   ELSE  TRUNCATE TABLE  z_CampaignLookup				
IF OBJECT_ID('dbo.z_ClientVersionCompatibility	', 'U') IS NULL    select top(0) * into z_ClientVersionCompatibility			 from  ClientVersionCompatibility       ELSE  TRUNCATE TABLE  z_ClientVersionCompatibility	
IF OBJECT_ID('dbo.z_ConfigCategory				', 'U') IS NULL    select top(0) * into z_ConfigCategory						 from  ConfigCategory                   ELSE  TRUNCATE TABLE  z_ConfigCategory				
IF OBJECT_ID('dbo.z_ConfigKey						', 'U') IS NULL    select top(0) * into z_ConfigKey							 from  ConfigKey                        ELSE  TRUNCATE TABLE  z_ConfigKey						
IF OBJECT_ID('dbo.z_ConfigLanguageStrings			', 'U') IS NULL    select top(0) * into z_ConfigLanguageStrings				 from  ConfigLanguageStrings            ELSE  TRUNCATE TABLE  z_ConfigLanguageStrings			
IF OBJECT_ID('dbo.z_ConfigValue					', 'U') IS NULL    select top(0) * into z_ConfigValue							 from  ConfigValue                      ELSE  TRUNCATE TABLE  z_ConfigValue					
IF OBJECT_ID('dbo.z_ContactRemarks				', 'U') IS NULL    select top(0) * into z_ContactRemarks						 from  ContactRemarks                   ELSE  TRUNCATE TABLE  z_ContactRemarks				
IF OBJECT_ID('dbo.z_DatastoreActions				', 'U') IS NULL    select top(0) * into z_DatastoreActions						 from  DatastoreActions             ELSE  TRUNCATE TABLE  z_DatastoreActions				
IF OBJECT_ID('dbo.z_DatastoreArchiveRules			', 'U') IS NULL    select top(0) * into z_DatastoreArchiveRules				 from  DatastoreArchiveRules            ELSE  TRUNCATE TABLE  z_DatastoreArchiveRules			
IF OBJECT_ID('dbo.z_DatastoreDetails				', 'U') IS NULL    select top(0) * into z_DatastoreDetails						 from  DatastoreDetails             ELSE  TRUNCATE TABLE  z_DatastoreDetails				
IF OBJECT_ID('dbo.z_DatastoreFile					', 'U') IS NULL    select top(0) * into z_DatastoreFile						 from  DatastoreFile                    ELSE  TRUNCATE TABLE  z_DatastoreFile					
IF OBJECT_ID('dbo.z_DatastoreFileDetails			', 'U') IS NULL    select top(0) * into z_DatastoreFileDetails					 from  DatastoreFileDetails         ELSE  TRUNCATE TABLE  z_DatastoreFileDetails			
IF OBJECT_ID('dbo.z_DatastorePurgeRules			', 'U') IS NULL    select top(0) * into z_DatastorePurgeRules					 from  DatastorePurgeRules              ELSE  TRUNCATE TABLE  z_DatastorePurgeRules			
IF OBJECT_ID('dbo.z_Datastores					', 'U') IS NULL    select top(0) * into z_Datastores							 from  Datastores                       ELSE  TRUNCATE TABLE  z_Datastores					
IF OBJECT_ID('dbo.z_DispositionNames				', 'U') IS NULL    select top(0) * into z_DispositionNames						 from  DispositionNames             ELSE  TRUNCATE TABLE  z_DispositionNames				
IF OBJECT_ID('dbo.z_Dnis							', 'U') IS NULL    select top(0) * into z_Dnis									 from  Dnis                         ELSE  TRUNCATE TABLE  z_Dnis							
IF OBJECT_ID('dbo.z_DnisGroup						', 'U') IS NULL    select top(0) * into z_DnisGroup							 from  DnisGroup                        ELSE  TRUNCATE TABLE  z_DnisGroup						
IF OBJECT_ID('dbo.z_Email							', 'U') IS NULL    select top(0) * into z_Email								 from  Email                            ELSE  TRUNCATE TABLE  z_Email							
IF OBJECT_ID('dbo.z_EmailGroup					', 'U') IS NULL    select top(0) * into z_EmailGroup							 from  EmailGroup                       ELSE  TRUNCATE TABLE  z_EmailGroup					
IF OBJECT_ID('dbo.z_Eval_Contact					', 'U') IS NULL    select top(0) * into z_Eval_Contact							 from  Eval_Contact                 ELSE  TRUNCATE TABLE  z_Eval_Contact					
IF OBJECT_ID('dbo.z_EvalCategory					', 'U') IS NULL    select top(0) * into z_EvalCategory							 from  EvalCategory                 ELSE  TRUNCATE TABLE  z_EvalCategory					
IF OBJECT_ID('dbo.z_EvalCriteria					', 'U') IS NULL    select top(0) * into z_EvalCriteria							 from  EvalCriteria                 ELSE  TRUNCATE TABLE  z_EvalCriteria					
IF OBJECT_ID('dbo.z_EvalCriteriaValue				', 'U') IS NULL    select top(0) * into z_EvalCriteriaValue					 from  EvalCriteriaValue                ELSE  TRUNCATE TABLE  z_EvalCriteriaValue				
IF OBJECT_ID('dbo.z_EvalEvaluation				', 'U') IS NULL    select top(0) * into z_EvalEvaluation						 from  EvalEvaluation                   ELSE  TRUNCATE TABLE  z_EvalEvaluation				
IF OBJECT_ID('dbo.z_EvalForm						', 'U') IS NULL    select top(0) * into z_EvalForm								 from  EvalForm                     ELSE  TRUNCATE TABLE  z_EvalForm						
IF OBJECT_ID('dbo.z_EvalLangString				', 'U') IS NULL    select top(0) * into z_EvalLangString						 from  EvalLangString                   ELSE  TRUNCATE TABLE  z_EvalLangString				
IF OBJECT_ID('dbo.z_EvalLangStringIds				', 'U') IS NULL    select top(0) * into z_EvalLangStringIds					 from  EvalLangStringIds                ELSE  TRUNCATE TABLE  z_EvalLangStringIds				
IF OBJECT_ID('dbo.z_EvalScore						', 'U') IS NULL    select top(0) * into z_EvalScore							 from  EvalScore                        ELSE  TRUNCATE TABLE  z_EvalScore						
IF OBJECT_ID('dbo.z_Fields						', 'U') IS NULL    select top(0) * into z_Fields								 from  Fields                           ELSE  TRUNCATE TABLE  z_Fields						
IF OBJECT_ID('dbo.z_Holiday						', 'U') IS NULL    select top(0) * into z_Holiday								 from  Holiday                          ELSE  TRUNCATE TABLE  z_Holiday						
IF OBJECT_ID('dbo.z_HolidayLocationMap			', 'U') IS NULL    select top(0) * into z_HolidayLocationMap					 from  HolidayLocationMap               ELSE  TRUNCATE TABLE  z_HolidayLocationMap			
IF OBJECT_ID('dbo.z_Holidays						', 'U') IS NULL    select top(0) * into z_Holidays								 from  Holidays                     ELSE  TRUNCATE TABLE  z_Holidays						
IF OBJECT_ID('dbo.z_iceWebSettings_AlertHistory	', 'U') IS NULL    select top(0) * into z_iceWebSettings_AlertHistory			 from  iceWebSettings_AlertHistory      ELSE  TRUNCATE TABLE  z_iceWebSettings_AlertHistory	
IF OBJECT_ID('dbo.z_iceWebSettings_Alerts			', 'U') IS NULL    select top(0) * into z_iceWebSettings_Alerts				 from  iceWebSettings_Alerts            ELSE  TRUNCATE TABLE  z_iceWebSettings_Alerts			
IF OBJECT_ID('dbo.z_iceWebSettings_HiddenItems	', 'U') IS NULL    select top(0) * into z_iceWebSettings_HiddenItems			 from  iceWebSettings_HiddenItems       ELSE  TRUNCATE TABLE  z_iceWebSettings_HiddenItems	
IF OBJECT_ID('dbo.z_iceWebSettings_NameValuePairs	', 'U') IS NULL    select top(0) * into z_iceWebSettings_NameValuePairs		 from  iceWebSettings_NameValuePairs    ELSE  TRUNCATE TABLE  z_iceWebSettings_NameValuePairs	
IF OBJECT_ID('dbo.z_iceWebSettings_StatFormats	', 'U') IS NULL    select top(0) * into z_iceWebSettings_StatFormats			 from  iceWebSettings_StatFormats       ELSE  TRUNCATE TABLE  z_iceWebSettings_StatFormats	
IF OBJECT_ID('dbo.z_IMAddress						', 'U') IS NULL    select top(0) * into z_IMAddress							 from  IMAddress                        ELSE  TRUNCATE TABLE  z_IMAddress						
IF OBJECT_ID('dbo.z_IMGroup						', 'U') IS NULL    select top(0) * into z_IMGroup								 from  IMGroup                          ELSE  TRUNCATE TABLE  z_IMGroup						
IF OBJECT_ID('dbo.z_IMRecording					', 'U') IS NULL    select top(0) * into z_IMRecording							 from  IMRecording                      ELSE  TRUNCATE TABLE  z_IMRecording					
IF OBJECT_ID('dbo.z_Languages						', 'U') IS NULL    select top(0) * into z_Languages							 from  Languages                        ELSE  TRUNCATE TABLE  z_Languages						
IF OBJECT_ID('dbo.z_LOBName						', 'U') IS NULL    select top(0) * into z_LOBName								 from  LOBName                          ELSE  TRUNCATE TABLE  z_LOBName						
IF OBJECT_ID('dbo.z_Locations						', 'U') IS NULL    select top(0) * into z_Locations							 from  Locations                        ELSE  TRUNCATE TABLE  z_Locations						
IF OBJECT_ID('dbo.z_Lock							', 'U') IS NULL    select top(0) * into z_Lock									 from  Lock                         ELSE  TRUNCATE TABLE  z_Lock							
IF OBJECT_ID('dbo.z_MergeRecordings				', 'U') IS NULL    select top(0) * into z_MergeRecordings						 from  MergeRecordings                  ELSE  TRUNCATE TABLE  z_MergeRecordings				
IF OBJECT_ID('dbo.z_MergeRecordingsFileInfo		', 'U') IS NULL    select top(0) * into z_MergeRecordingsFileInfo				 from  MergeRecordingsFileInfo          ELSE  TRUNCATE TABLE  z_MergeRecordingsFileInfo		
IF OBJECT_ID('dbo.z_Node							', 'U') IS NULL    select top(0) * into z_Node									 from  Node                         ELSE  TRUNCATE TABLE  z_Node							
IF OBJECT_ID('dbo.z_NotReadyReasonName			', 'U') IS NULL    select top(0) * into z_NotReadyReasonName					 from  NotReadyReasonName               ELSE  TRUNCATE TABLE  z_NotReadyReasonName			
IF OBJECT_ID('dbo.z_OperatingDates				', 'U') IS NULL    select top(0) * into z_OperatingDates						 from  OperatingDates                   ELSE  TRUNCATE TABLE  z_OperatingDates				
IF OBJECT_ID('dbo.z_ProspectList					', 'U') IS NULL    select top(0) * into z_ProspectList							 from  ProspectList                 ELSE  TRUNCATE TABLE  z_ProspectList					
IF OBJECT_ID('dbo.z_PVars_Purging					', 'U') IS NULL    select top(0) * into z_PVars_Purging						 from  PVars_Purging                    ELSE  TRUNCATE TABLE  z_PVars_Purging					
IF OBJECT_ID('dbo.z_QueueIDLookup					', 'U') IS NULL    select top(0) * into z_QueueIDLookup						 from  QueueIDLookup                    ELSE  TRUNCATE TABLE  z_QueueIDLookup					
IF OBJECT_ID('dbo.z_RecordingOptions				', 'U') IS NULL    select top(0) * into z_RecordingOptions						 from  RecordingOptions             ELSE  TRUNCATE TABLE  z_RecordingOptions				
IF OBJECT_ID('dbo.z_Recordings					', 'U') IS NULL    select top(0) * into z_Recordings							 from  Recordings                       ELSE  TRUNCATE TABLE  z_Recordings					
IF OBJECT_ID('dbo.z_RecordingSchedules			', 'U') IS NULL    select top(0) * into z_RecordingSchedules					 from  RecordingSchedules               ELSE  TRUNCATE TABLE  z_RecordingSchedules			
IF OBJECT_ID('dbo.z_RecordingsFaultedFiles		', 'U') IS NULL    select top(0) * into z_RecordingsFaultedFiles				 from  RecordingsFaultedFiles           ELSE  TRUNCATE TABLE  z_RecordingsFaultedFiles		
IF OBJECT_ID('dbo.z_RequiredSkill					', 'U') IS NULL    select top(0) * into z_RequiredSkill						 from  RequiredSkill                    ELSE  TRUNCATE TABLE  z_RequiredSkill					
IF OBJECT_ID('dbo.z_RoutingRule					', 'U') IS NULL    select top(0) * into z_RoutingRule							 from  RoutingRule                      ELSE  TRUNCATE TABLE  z_RoutingRule					
IF OBJECT_ID('dbo.z_ScreenRecordingParameters		', 'U') IS NULL    select top(0) * into z_ScreenRecordingParameters			 from  ScreenRecordingParameters        ELSE  TRUNCATE TABLE  z_ScreenRecordingParameters		
IF OBJECT_ID('dbo.z_ScreenRecordingServerConfig	', 'U') IS NULL    select top(0) * into z_ScreenRecordingServerConfig			 from  ScreenRecordingServerConfig      ELSE  TRUNCATE TABLE  z_ScreenRecordingServerConfig	
IF OBJECT_ID('dbo.z_ScreenRecordingVendorInfo		', 'U') IS NULL    select top(0) * into z_ScreenRecordingVendorInfo			 from  ScreenRecordingVendorInfo        ELSE  TRUNCATE TABLE  z_ScreenRecordingVendorInfo		
IF OBJECT_ID('dbo.z_SIPGroup						', 'U') IS NULL    select top(0) * into z_SIPGroup								 from  SIPGroup                     ELSE  TRUNCATE TABLE  z_SIPGroup						
IF OBJECT_ID('dbo.z_SIPGroupCodec					', 'U') IS NULL    select top(0) * into z_SIPGroupCodec						 from  SIPGroupCodec                    ELSE  TRUNCATE TABLE  z_SIPGroupCodec					
IF OBJECT_ID('dbo.z_SIPGroupIdentity				', 'U') IS NULL    select top(0) * into z_SIPGroupIdentity						 from  SIPGroupIdentity             ELSE  TRUNCATE TABLE  z_SIPGroupIdentity				
IF OBJECT_ID('dbo.z_SIPGroupTrustedDomain			', 'U') IS NULL    select top(0) * into z_SIPGroupTrustedDomain				 from  SIPGroupTrustedDomain            ELSE  TRUNCATE TABLE  z_SIPGroupTrustedDomain			
IF OBJECT_ID('dbo.z_SIPPort						', 'U') IS NULL    select top(0) * into z_SIPPort								 from  SIPPort                          ELSE  TRUNCATE TABLE  z_SIPPort						
IF OBJECT_ID('dbo.z_Site							', 'U') IS NULL    select top(0) * into z_Site									 from  Site                         ELSE  TRUNCATE TABLE  z_Site							
IF OBJECT_ID('dbo.z_Skill							', 'U') IS NULL    select top(0) * into z_Skill								 from  Skill                            ELSE  TRUNCATE TABLE  z_Skill							
IF OBJECT_ID('dbo.z_StartOfDayProspectCounts		', 'U') IS NULL    select top(0) * into z_StartOfDayProspectCounts				 from  StartOfDayProspectCounts     ELSE  TRUNCATE TABLE  z_StartOfDayProspectCounts		
IF OBJECT_ID('dbo.z_Stat_ADR						', 'U') IS NULL    select top(0) * into z_Stat_ADR								 from  Stat_ADR                     ELSE  TRUNCATE TABLE  z_Stat_ADR						
IF OBJECT_ID('dbo.z_Stat_AgentActivity_D			', 'U') IS NULL    select top(0) * into z_Stat_AgentActivity_D					 from  Stat_AgentActivity_D         ELSE  TRUNCATE TABLE  z_Stat_AgentActivity_D			
IF OBJECT_ID('dbo.z_Stat_AgentActivity_I			', 'U') IS NULL    select top(0) * into z_Stat_AgentActivity_I					 from  Stat_AgentActivity_I         ELSE  TRUNCATE TABLE  z_Stat_AgentActivity_I			
IF OBJECT_ID('dbo.z_Stat_AgentActivity_M			', 'U') IS NULL    select top(0) * into z_Stat_AgentActivity_M					 from  Stat_AgentActivity_M         ELSE  TRUNCATE TABLE  z_Stat_AgentActivity_M			
IF OBJECT_ID('dbo.z_Stat_AgentActivity_W			', 'U') IS NULL    select top(0) * into z_Stat_AgentActivity_W					 from  Stat_AgentActivity_W         ELSE  TRUNCATE TABLE  z_Stat_AgentActivity_W			
IF OBJECT_ID('dbo.z_Stat_AgentActivity_Y			', 'U') IS NULL    select top(0) * into z_Stat_AgentActivity_Y					 from  Stat_AgentActivity_Y         ELSE  TRUNCATE TABLE  z_Stat_AgentActivity_Y			
IF OBJECT_ID('dbo.z_Stat_AgentActivityByQueue_D	', 'U') IS NULL    select top(0) * into z_Stat_AgentActivityByQueue_D			 from  Stat_AgentActivityByQueue_D      ELSE  TRUNCATE TABLE  z_Stat_AgentActivityByQueue_D	
IF OBJECT_ID('dbo.z_Stat_AgentActivityByQueue_I	', 'U') IS NULL    select top(0) * into z_Stat_AgentActivityByQueue_I			 from  Stat_AgentActivityByQueue_I      ELSE  TRUNCATE TABLE  z_Stat_AgentActivityByQueue_I	
IF OBJECT_ID('dbo.z_Stat_AgentActivityByQueue_M	', 'U') IS NULL    select top(0) * into z_Stat_AgentActivityByQueue_M			 from  Stat_AgentActivityByQueue_M      ELSE  TRUNCATE TABLE  z_Stat_AgentActivityByQueue_M	
IF OBJECT_ID('dbo.z_Stat_AgentActivityByQueue_W	', 'U') IS NULL    select top(0) * into z_Stat_AgentActivityByQueue_W			 from  Stat_AgentActivityByQueue_W      ELSE  TRUNCATE TABLE  z_Stat_AgentActivityByQueue_W	
IF OBJECT_ID('dbo.z_Stat_AgentActivityByQueue_Y	', 'U') IS NULL    select top(0) * into z_Stat_AgentActivityByQueue_Y			 from  Stat_AgentActivityByQueue_Y      ELSE  TRUNCATE TABLE  z_Stat_AgentActivityByQueue_Y	
IF OBJECT_ID('dbo.z_Stat_AgentLineOfBusiness_D	', 'U') IS NULL    select top(0) * into z_Stat_AgentLineOfBusiness_D			 from  Stat_AgentLineOfBusiness_D       ELSE  TRUNCATE TABLE  z_Stat_AgentLineOfBusiness_D	
IF OBJECT_ID('dbo.z_Stat_AgentLineOfBusiness_I	', 'U') IS NULL    select top(0) * into z_Stat_AgentLineOfBusiness_I			 from  Stat_AgentLineOfBusiness_I       ELSE  TRUNCATE TABLE  z_Stat_AgentLineOfBusiness_I	
IF OBJECT_ID('dbo.z_Stat_AgentLineOfBusiness_M	', 'U') IS NULL    select top(0) * into z_Stat_AgentLineOfBusiness_M			 from  Stat_AgentLineOfBusiness_M       ELSE  TRUNCATE TABLE  z_Stat_AgentLineOfBusiness_M	
IF OBJECT_ID('dbo.z_Stat_AgentLineOfBusiness_W	', 'U') IS NULL    select top(0) * into z_Stat_AgentLineOfBusiness_W			 from  Stat_AgentLineOfBusiness_W       ELSE  TRUNCATE TABLE  z_Stat_AgentLineOfBusiness_W	
IF OBJECT_ID('dbo.z_Stat_AgentLineOfBusiness_Y	', 'U') IS NULL    select top(0) * into z_Stat_AgentLineOfBusiness_Y			 from  Stat_AgentLineOfBusiness_Y       ELSE  TRUNCATE TABLE  z_Stat_AgentLineOfBusiness_Y	
IF OBJECT_ID('dbo.z_Stat_AgentNotReadyBreakdown_D	', 'U') IS NULL    select top(0) * into z_Stat_AgentNotReadyBreakdown_D		 from  Stat_AgentNotReadyBreakdown_D    ELSE  TRUNCATE TABLE  z_Stat_AgentNotReadyBreakdown_D	
IF OBJECT_ID('dbo.z_Stat_AgentNotReadyBreakdown_I	', 'U') IS NULL    select top(0) * into z_Stat_AgentNotReadyBreakdown_I		 from  Stat_AgentNotReadyBreakdown_I    ELSE  TRUNCATE TABLE  z_Stat_AgentNotReadyBreakdown_I	
IF OBJECT_ID('dbo.z_Stat_AgentNotReadyBreakdown_M	', 'U') IS NULL    select top(0) * into z_Stat_AgentNotReadyBreakdown_M		 from  Stat_AgentNotReadyBreakdown_M    ELSE  TRUNCATE TABLE  z_Stat_AgentNotReadyBreakdown_M	
IF OBJECT_ID('dbo.z_Stat_AgentNotReadyBreakdown_W	', 'U') IS NULL    select top(0) * into z_Stat_AgentNotReadyBreakdown_W		 from  Stat_AgentNotReadyBreakdown_W    ELSE  TRUNCATE TABLE  z_Stat_AgentNotReadyBreakdown_W	
IF OBJECT_ID('dbo.z_Stat_AgentNotReadyBreakdown_Y	', 'U') IS NULL    select top(0) * into z_Stat_AgentNotReadyBreakdown_Y		 from  Stat_AgentNotReadyBreakdown_Y    ELSE  TRUNCATE TABLE  z_Stat_AgentNotReadyBreakdown_Y	
IF OBJECT_ID('dbo.z_Stat_CDR						', 'U') IS NULL    select top(0) * into z_Stat_CDR								 from  Stat_CDR                     ELSE  TRUNCATE TABLE  z_Stat_CDR						
IF OBJECT_ID('dbo.z_Stat_CDR_LastSummarized		', 'U') IS NULL    select top(0) * into z_Stat_CDR_LastSummarized				 from  Stat_CDR_LastSummarized          ELSE  TRUNCATE TABLE  z_Stat_CDR_LastSummarized		
IF OBJECT_ID('dbo.z_Stat_CDR_Summary				', 'U') IS NULL    select top(0) * into z_Stat_CDR_Summary						 from  Stat_CDR_Summary             ELSE  TRUNCATE TABLE  z_Stat_CDR_Summary				
IF OBJECT_ID('dbo.z_Stat_DNISActivity_D			', 'U') IS NULL    select top(0) * into z_Stat_DNISActivity_D					 from  Stat_DNISActivity_D              ELSE  TRUNCATE TABLE  z_Stat_DNISActivity_D			
IF OBJECT_ID('dbo.z_Stat_DNISActivity_I			', 'U') IS NULL    select top(0) * into z_Stat_DNISActivity_I					 from  Stat_DNISActivity_I              ELSE  TRUNCATE TABLE  z_Stat_DNISActivity_I			
IF OBJECT_ID('dbo.z_Stat_DNISActivity_M			', 'U') IS NULL    select top(0) * into z_Stat_DNISActivity_M					 from  Stat_DNISActivity_M              ELSE  TRUNCATE TABLE  z_Stat_DNISActivity_M			
IF OBJECT_ID('dbo.z_Stat_DNISActivity_W			', 'U') IS NULL    select top(0) * into z_Stat_DNISActivity_W					 from  Stat_DNISActivity_W              ELSE  TRUNCATE TABLE  z_Stat_DNISActivity_W			
IF OBJECT_ID('dbo.z_Stat_DNISActivity_Y			', 'U') IS NULL    select top(0) * into z_Stat_DNISActivity_Y					 from  Stat_DNISActivity_Y              ELSE  TRUNCATE TABLE  z_Stat_DNISActivity_Y			
IF OBJECT_ID('dbo.z_Stat_QueueActivity_D			', 'U') IS NULL    select top(0) * into z_Stat_QueueActivity_D					 from  Stat_QueueActivity_D         ELSE  TRUNCATE TABLE  z_Stat_QueueActivity_D			
IF OBJECT_ID('dbo.z_Stat_QueueActivity_I			', 'U') IS NULL    select top(0) * into z_Stat_QueueActivity_I					 from  Stat_QueueActivity_I         ELSE  TRUNCATE TABLE  z_Stat_QueueActivity_I			
IF OBJECT_ID('dbo.z_Stat_QueueActivity_M			', 'U') IS NULL    select top(0) * into z_Stat_QueueActivity_M					 from  Stat_QueueActivity_M         ELSE  TRUNCATE TABLE  z_Stat_QueueActivity_M			
IF OBJECT_ID('dbo.z_Stat_QueueActivity_W			', 'U') IS NULL    select top(0) * into z_Stat_QueueActivity_W					 from  Stat_QueueActivity_W         ELSE  TRUNCATE TABLE  z_Stat_QueueActivity_W			
IF OBJECT_ID('dbo.z_Stat_QueueActivity_Y			', 'U') IS NULL    select top(0) * into z_Stat_QueueActivity_Y					 from  Stat_QueueActivity_Y         ELSE  TRUNCATE TABLE  z_Stat_QueueActivity_Y			
IF OBJECT_ID('dbo.z_Stat_SkillActivity_D			', 'U') IS NULL    select top(0) * into z_Stat_SkillActivity_D					 from  Stat_SkillActivity_D         ELSE  TRUNCATE TABLE  z_Stat_SkillActivity_D			
IF OBJECT_ID('dbo.z_Stat_SkillActivity_I			', 'U') IS NULL    select top(0) * into z_Stat_SkillActivity_I					 from  Stat_SkillActivity_I         ELSE  TRUNCATE TABLE  z_Stat_SkillActivity_I			
IF OBJECT_ID('dbo.z_Stat_SkillActivity_M			', 'U') IS NULL    select top(0) * into z_Stat_SkillActivity_M					 from  Stat_SkillActivity_M         ELSE  TRUNCATE TABLE  z_Stat_SkillActivity_M			
IF OBJECT_ID('dbo.z_Stat_SkillActivity_W			', 'U') IS NULL    select top(0) * into z_Stat_SkillActivity_W					 from  Stat_SkillActivity_W         ELSE  TRUNCATE TABLE  z_Stat_SkillActivity_W			
IF OBJECT_ID('dbo.z_Stat_SkillActivity_Y			', 'U') IS NULL    select top(0) * into z_Stat_SkillActivity_Y					 from  Stat_SkillActivity_Y         ELSE  TRUNCATE TABLE  z_Stat_SkillActivity_Y			
IF OBJECT_ID('dbo.z_Stat_TrunkActivity_D			', 'U') IS NULL    select top(0) * into z_Stat_TrunkActivity_D					 from  Stat_TrunkActivity_D         ELSE  TRUNCATE TABLE  z_Stat_TrunkActivity_D			
IF OBJECT_ID('dbo.z_Stat_TrunkActivity_I			', 'U') IS NULL    select top(0) * into z_Stat_TrunkActivity_I					 from  Stat_TrunkActivity_I         ELSE  TRUNCATE TABLE  z_Stat_TrunkActivity_I			
IF OBJECT_ID('dbo.z_Stat_TrunkActivity_M			', 'U') IS NULL    select top(0) * into z_Stat_TrunkActivity_M					 from  Stat_TrunkActivity_M         ELSE  TRUNCATE TABLE  z_Stat_TrunkActivity_M			
IF OBJECT_ID('dbo.z_Stat_TrunkActivity_W			', 'U') IS NULL    select top(0) * into z_Stat_TrunkActivity_W					 from  Stat_TrunkActivity_W         ELSE  TRUNCATE TABLE  z_Stat_TrunkActivity_W			
IF OBJECT_ID('dbo.z_Stat_TrunkActivity_Y			', 'U') IS NULL    select top(0) * into z_Stat_TrunkActivity_Y					 from  Stat_TrunkActivity_Y         ELSE  TRUNCATE TABLE  z_Stat_TrunkActivity_Y			
IF OBJECT_ID('dbo.z_Stat_WorkflowActionActivity_D	', 'U') IS NULL    select top(0) * into z_Stat_WorkflowActionActivity_D		 from  Stat_WorkflowActionActivity_D    ELSE  TRUNCATE TABLE  z_Stat_WorkflowActionActivity_D	
IF OBJECT_ID('dbo.z_Stat_WorkflowActionActivity_I	', 'U') IS NULL    select top(0) * into z_Stat_WorkflowActionActivity_I		 from  Stat_WorkflowActionActivity_I    ELSE  TRUNCATE TABLE  z_Stat_WorkflowActionActivity_I	
IF OBJECT_ID('dbo.z_Stat_WorkflowActionActivity_M	', 'U') IS NULL    select top(0) * into z_Stat_WorkflowActionActivity_M		 from  Stat_WorkflowActionActivity_M    ELSE  TRUNCATE TABLE  z_Stat_WorkflowActionActivity_M	
IF OBJECT_ID('dbo.z_Stat_WorkflowActionActivity_W	', 'U') IS NULL    select top(0) * into z_Stat_WorkflowActionActivity_W		 from  Stat_WorkflowActionActivity_W    ELSE  TRUNCATE TABLE  z_Stat_WorkflowActionActivity_W	
IF OBJECT_ID('dbo.z_Stat_WorkflowActionActivity_Y	', 'U') IS NULL    select top(0) * into z_Stat_WorkflowActionActivity_Y		 from  Stat_WorkflowActionActivity_Y    ELSE  TRUNCATE TABLE  z_Stat_WorkflowActionActivity_Y	
IF OBJECT_ID('dbo.z_StatVersion					', 'U') IS NULL    select top(0) * into z_StatVersion							 from  StatVersion                      ELSE  TRUNCATE TABLE  z_StatVersion					
IF OBJECT_ID('dbo.z_Switch						', 'U') IS NULL    select top(0) * into z_Switch								 from  Switch                           ELSE  TRUNCATE TABLE  z_Switch						
IF OBJECT_ID('dbo.z_Team							', 'U') IS NULL    select top(0) * into z_Team									 from  Team                         ELSE  TRUNCATE TABLE  z_Team							
IF OBJECT_ID('dbo.z_TeamAssignment				', 'U') IS NULL    select top(0) * into z_TeamAssignment						 from  TeamAssignment                   ELSE  TRUNCATE TABLE  z_TeamAssignment				
IF OBJECT_ID('dbo.z_Trunk							', 'U') IS NULL    select top(0) * into z_Trunk								 from  Trunk                            ELSE  TRUNCATE TABLE  z_Trunk							
IF OBJECT_ID('dbo.z_TrunkGroup					', 'U') IS NULL    select top(0) * into z_TrunkGroup							 from  TrunkGroup                       ELSE  TRUNCATE TABLE  z_TrunkGroup					
IF OBJECT_ID('dbo.z_UCAddress						', 'U') IS NULL    select top(0) * into z_UCAddress							 from  UCAddress                        ELSE  TRUNCATE TABLE  z_UCAddress						
IF OBJECT_ID('dbo.z_UCGroup						', 'U') IS NULL    select top(0) * into z_UCGroup								 from  UCGroup                          ELSE  TRUNCATE TABLE  z_UCGroup						
IF OBJECT_ID('dbo.z_WaitingList					', 'U') IS NULL    select top(0) * into z_WaitingList							 from  WaitingList                      ELSE  TRUNCATE TABLE  z_WaitingList					
IF OBJECT_ID('dbo.z_WfAction						', 'U') IS NULL    select top(0) * into z_WfAction								 from  WfAction                     ELSE  TRUNCATE TABLE  z_WfAction						
IF OBJECT_ID('dbo.z_WfAttributeDetail				', 'U') IS NULL    select top(0) * into z_WfAttributeDetail					 from  WfAttributeDetail                ELSE  TRUNCATE TABLE  z_WfAttributeDetail				
IF OBJECT_ID('dbo.z_WfGraph						', 'U') IS NULL    select top(0) * into z_WfGraph								 from  WfGraph                          ELSE  TRUNCATE TABLE  z_WfGraph						
IF OBJECT_ID('dbo.z_WfLink						', 'U') IS NULL    select top(0) * into z_WfLink								 from  WfLink                           ELSE  TRUNCATE TABLE  z_WfLink						
IF OBJECT_ID('dbo.z_WfLinkDetail					', 'U') IS NULL    select top(0) * into z_WfLinkDetail							 from  WfLinkDetail                 ELSE  TRUNCATE TABLE  z_WfLinkDetail					
IF OBJECT_ID('dbo.z_WfPage						', 'U') IS NULL    select top(0) * into z_WfPage								 from  WfPage                           ELSE  TRUNCATE TABLE  z_WfPage						
IF OBJECT_ID('dbo.z_WfSubApplication				', 'U') IS NULL    select top(0) * into z_WfSubApplication						 from  WfSubApplication             ELSE  TRUNCATE TABLE  z_WfSubApplication				
IF OBJECT_ID('dbo.z_WfSubAppMethod				', 'U') IS NULL    select top(0) * into z_WfSubAppMethod						 from  WfSubAppMethod                   ELSE  TRUNCATE TABLE  z_WfSubAppMethod				
IF OBJECT_ID('dbo.z_WfVariables					', 'U') IS NULL    select top(0) * into z_WfVariables							 from  WfVariables                      ELSE  TRUNCATE TABLE  z_WfVariables					
IF OBJECT_ID('dbo.z_zDBVersion                    ', 'U') IS NULL    select top(0) * into z_zDBVersion                            from  zDBVersion                      ELSE  TRUNCATE TABLE  z_zDBVersion                    